### ISSUE TITLE
Make a mechanism that If anyone change any details of students profile then it need to be reflect only in the active recruitment drive not in the past recruitement drive

### ISSUE THREAD

**Issue by itsGyanendra** [spo-iitk/ras-backend#79]

**Comment by 1-Harshit** [comment]
@abhishekshree Don't see a way to do this

**Comment by abhishekshree** [comment]
I don't think it's possible in the current architecture, also most of the details are copied while adding students to RC and that is changed, so I don't see a real problem where it will matter.

**Comment by itsGyanendra** [comment]
Add a option in the current RC to update profile
